### ISSUE TITLE
com.example is a single name instead of two separate directories.

### ISSUE THREAD

**Issue by karlnicholas** [eladchen/rest-easy-cdi#5]
com.example should be com/example.

**Comment by eladchen** [comment]
Hi, 

Thanks for fixing this. 

Could you please elaborate why pom.xml was added? I'm assuming for easy usage with Maven?

**Comment by karlnicholas** [comment]
Yea, pom.xml is just easier for me since I really haven't really sorted out gradle yet. Plus I might guess that you are using IntelliJ which I think is more gradle friendly. I am using Eclipse which I think is more maven friendly.

**Comment by eladchen** [comment]
Got it.

I'll merge this later as I'm away from my laptop.
